extract_version:
  provider: 'file'
  file:
    file: 'main.py'
    regex: 'VERSION = "(.+)"'

rpm: &rpm
  installable_package_name: 'omnipackage_example_python'
  build_dependencies: ['python3-devel', 'python3-pip']
  runtime_dependencies: ['python3']
  rpm:
    spec_template: '.omnipackage/specfile.spec.liquid'

deb: &deb
  installable_package_name: 'omnipackage-example-python'
  build_dependencies: ['python3-dev', 'python3-pip']
  runtime_dependencies: ['python3']
  deb:
    debian_templates: '.omnipackage/deb'

builds:
- distro: 'opensuse_15.3'
  <<: *rpm

- distro: 'opensuse_15.4'
  <<: *rpm

- distro: 'opensuse_15.5'
  <<: *rpm

- distro: 'opensuse_15.6'
  <<: *rpm

- distro: 'opensuse_tumbleweed'
  <<: *rpm

- distro: 'fedora_38'
  <<: *rpm

- distro: 'fedora_39'
  <<: *rpm

- distro: 'fedora_40'
  <<: *rpm

- distro: 'fedora_41'
  <<: *rpm

- distro: 'fedora_rawhide'
  <<: *rpm

- distro: 'debian_10'
  <<: *deb
  before_build_script: '.omnipackage/install_python.sh'
  build_dependencies: [build-essential, gdb, lcov, pkg-config, libbz2-dev, libffi-dev, libgdbm-dev, libgdbm-compat-dev, liblzma-dev, libncurses5-dev, libreadline6-dev, libsqlite3-dev, libssl-dev, lzma, lzma-dev, tk-dev, uuid-dev, zlib1g-dev]
  runtime_dependencies: []

- distro: 'debian_11'
  <<: *deb

- distro: 'debian_12'
  <<: *deb

- distro: 'debian_testing'
  <<: *deb

- distro: 'debian_unstable'
  <<: *deb

- distro: 'ubuntu_20.04'
  <<: *deb

- distro: 'ubuntu_22.04'
  <<: *deb

- distro: 'ubuntu_24.04'
  <<: *deb

- distro: 'almalinux_8'
  <<: *rpm

- distro: 'almalinux_9'
  <<: *rpm

- distro: 'rockylinux_8'
  <<: *rpm

- distro: 'rockylinux_9'
  <<: *rpm

- distro: 'mageia_8'
  <<: *rpm

- distro: 'mageia_9'
  <<: *rpm

- distro: 'mageia_cauldron'
  <<: *rpm
