# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in omnipackage_example_ruby.gemspec
gemspec

group :development do
  gem "rake"
  gem "minitest"
  gem "rubocop"
end
